version: '3'

services:
  nginx:
    image: registry.gitlab.com/ghostnoop/gilyazov_itis_python2k_project_11900/nginx:latest
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - app
    volumes:
      - static:/app/static

  app: &app
    image: registry.gitlab.com/ghostnoop/gilyazov_itis_python2k_project_11900:latest
    build:
      dockerfile: deploy/python/Dockerfile
      context: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DEBUG: 'True'
      REDIS_CONNECTION: redis://redis:6379/0
    volumes:
      - static:/app/static

  celery:
    <<: *app
    working_dir: /app/src
    command: celery -A core worker -l INFO -Q default -B
    ports: []
    volumes: []

  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: webmonitoring
      POSTGRES_USER: webmonitoring
      POSTGRES_PASSWORD: webmonitoring
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine

volumes:
  db:
  static:
