# Generated by Django 3.1.7 on 2021-03-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
        migrations.AddField(
            model_name="client",
            name="confirm_code",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.confirmcode",
            ),
        ),
        migrations.AddField(
            model_name="executor",
            name="confirm_code",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.confirmcode",
            ),
        ),
    ]
