# Generated by Django 3.1.6 on 2021-03-11 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_executor_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="executor_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.executor",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="point_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.point"
            ),
        ),
    ]
