# Generated by Django 3.1.6 on 2021-03-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20210312_0001"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="point",
            name="deleted",
        ),
    ]
