# Generated by Django 3.1.6 on 2021-04-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20210313_1937"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={},
        ),
        migrations.AlterModelOptions(
            name="client",
            options={},
        ),
        migrations.AlterModelOptions(
            name="clientfeedback",
            options={},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={},
        ),
        migrations.AlterModelOptions(
            name="dispute",
            options={},
        ),
        migrations.AlterModelOptions(
            name="disputecomment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="disputestatus",
            options={},
        ),
        migrations.AlterModelOptions(
            name="executor",
            options={},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterModelOptions(
            name="point",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pointnotification",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pointphoto",
            options={},
        ),
        migrations.AlterModelOptions(
            name="relation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={},
        ),
    ]
