# Generated by Django 3.1.6 on 2021-05-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20210427_1453"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientfeedback",
            old_name="client_id",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="dispute",
            old_name="order_id",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="dispute",
            old_name="status_id",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="disputecomment",
            old_name="dispute_id",
            new_name="dispute",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="client_id",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="executor_id",
            new_name="executor",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="point_id",
            new_name="point",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="status_id",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="point",
            old_name="creator_id",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="point",
            old_name="relation_id",
            new_name="relation",
        ),
        migrations.RenameField(
            model_name="pointnotification",
            old_name="point_id",
            new_name="point",
        ),
        migrations.RenameField(
            model_name="pointphoto",
            old_name="point_id",
            new_name="point",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="executor_id",
            new_name="executor",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="parent_id",
            new_name="parent",
        ),
    ]
