# Generated by Django 3.1.6 on 2021-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20210509_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="point",
            name="avatar",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="point",
            name="comment",
            field=models.TextField(null=True),
        ),
    ]
